### ISSUE TITLE
ユーザー管理アプリ

### ISSUE THREAD

**Issue by MasahiroToyooka** [MasahiroToyooka/UserList_TableView#1]
## 仕様
- キャンプ参加生の全員のリスト（ユーザーリスト）を作成します。リストはボタンを並べて作ってください。
- 名前と趣味（自由欄）の表示内容はソースコードに定義します。
- Aさんのボタンが押されると、ソースコードに定義した名前と趣味の情報をユーザーデータ画面へ渡し表示させます。
- 画面の遷移は「segue」を使います。
- ナビゲーションコントローラーを設定してください。（「画面遷移->戻る」が簡単になります。）

**Comment by kanadayusaku** [comment]
(1) 13〜28行目：メンバーのデータを配列に格納するに当たって、格納する値をソースコードにベタがきするのは拡張性、保守性の観点から実はあまりよくないです。
    （人が増えるたびにソース修正する手間がかかるので。。。）
CSV,JSONなど、別ファイルに記載してそのファイルを読み込む関数を作成した方が良いと思います。

  (2) 13〜28行目：古いバージョンではstructを使用して、ユーザ名と趣味を格納していますが、そちらの方が良いと思います。　（プロトコル指向）
      後は、structで定義した変数のprivate化やprivate化した変数に値を代入、値を出力するpublic関数を追加してあげればカプセル化の要素も取り入れた、さらに良いプログラムになるかと思います。

  (3) 40行目：戻り値として固定値を使用するなら、定数として宣言した方が良いかと思います。
　　また、今回のパターンでは、「members.count」で配列の個数を取得できます。
　　structを使用する場合はreturnの前にユーザ情報を配列に格納する関数を入れてあげれば問題ないかと思います。
